pipeline:
  - name: aaaa
    command: aaaaa
  - name: test
    type: command
    command: echo foo && echo foo && echo foo && echo foo && sleep 1
  - name: parallel
    parallel:
      - name: echo bar
        command: echo bar && sleep 2
      - name: fail 
        command: ls aaaaaa
service:
  type: github
  token: $WALTER_GITHUB_TOKEN

messenger:
  type: slack
  channel: random
  url: $SLACK_WEBHOOK_URL
  icon_url: https://raw.githubusercontent.com/serverspec/serverspec-integration-test/master/walter.png
  username: Walter
  suppress:
    - result
    
